"HDUNGEON for
		HOLLOW HOUSE
	Rooms and objects. Built on the Zork I engine (Infocom), MIT license."

<DIRECTIONS NORTH EAST WEST SOUTH NE NW SE SW UP DOWN IN OUT LAND>

<GLOBAL SCORE-MAX 0>

<GLOBAL FALSE-FLAG <>>

"global flag that the well exits test"

<GLOBAL BUCKET-DOWN <>>

"---------- things the engine expects to exist ----------"

<OBJECT GLOBAL-WATER
	(IN LOCAL-GLOBALS)
	(SYNONYM WATER)
	(ADJECTIVE BLACK COLD)
	(DESC "water")
	(FLAGS DRINKBIT)
	(ACTION WATER-F)>

<OBJECT WATER
	(IN LOCAL-GLOBALS)
	(SYNONYM PUDDLE)
	(DESC "puddle")
	(FLAGS DRINKBIT NONLANDBIT)
	(ACTION WATER-F)>

<OBJECT WALL
	(IN GLOBAL-OBJECTS)
	(SYNONYM WALL WALLS)
	(DESC "wall")>

"---------- outside ----------"

<OBJECT WHITE-HOUSE
	(IN LOCAL-GLOBALS)
	(SYNONYM HOUSE HOME)
	(ADJECTIVE WHITE)
	(DESC "white house")
	(FLAGS NDESCBIT)
	(ACTION WHITE-HOUSE-F)>

<OBJECT BOARDS
	(IN LOCAL-GLOBALS)
	(SYNONYM BOARDS BOARD PLANKS NAILS)
	(ADJECTIVE FRONT BOARDED)
	(DESC "boarded front door")
	(FLAGS NDESCBIT)
	(ACTION BOARDS-F)>

<OBJECT LIT-WINDOW
	(IN LOCAL-GLOBALS)
	(SYNONYM LIGHT GLOW)
	(ADJECTIVE YELLOW)
	(DESC "yellow light")
	(FLAGS NDESCBIT)
	(ACTION LIT-WINDOW-F)>

<OBJECT MAILBOX
	(IN WEST-OF-HOUSE)
	(SYNONYM MAILBOX BOX)
	(ADJECTIVE SMALL RUSTED)
	(DESC "rusted mailbox")
	(FLAGS CONTBIT TRYTAKEBIT)
	(CAPACITY 5)
	(ACTION MAILBOX-F)>

<OBJECT NOTE
	(IN MAILBOX)
	(SYNONYM NOTE PAPER LETTER HANDWRITING)
	(ADJECTIVE FOLDED CREASED)
	(DESC "folded note")
	(FLAGS READBIT TAKEBIT BURNBIT)
	(SIZE 1)
	(ACTION NOTE-F)>

<OBJECT SWING
	(IN NORTH-OF-HOUSE)
	(SYNONYM SWING SWINGS CHAIN CHAINS)
	(ADJECTIVE RUSTED OLD)
	(DESC "swing set")
	(FLAGS NDESCBIT)
	(ACTION SWING-F)>

<OBJECT KITCHEN-WINDOW
	(IN LOCAL-GLOBALS)
	(SYNONYM WINDOW)
	(ADJECTIVE KITCHEN SMALL)
	(DESC "kitchen window")
	(FLAGS DOORBIT NDESCBIT)
	(ACTION KITCHEN-WINDOW-F)>

<OBJECT WELL
	(IN WELL-TOP)
	(SYNONYM WELL HOLE STONES SHAFT)
	(ADJECTIVE OLD STONE DEEP)
	(DESC "old well")
	(FLAGS NDESCBIT)
	(ACTION WELL-F)>

<OBJECT BUCKET
	(IN WELL-TOP)
	(SYNONYM BUCKET WINCH CRANK)
	(ADJECTIVE WOODEN)
	(DESC "bucket")
	(FLAGS NDESCBIT TRYTAKEBIT)
	(ACTION BUCKET-F)>

"---------- the kitchen ----------"

<OBJECT MOTHER
	(IN KITCHEN)
	(SYNONYM MOTHER MOM WOMAN LENA)
	(ADJECTIVE SMILING)
	(DESC "Mother")
	(FLAGS ACTORBIT NDESCBIT)
	(ACTION MOTHER-F)>

<OBJECT STOVE
	(IN KITCHEN)
	(SYNONYM STOVE OVEN BURNER)
	(DESC "stove")
	(FLAGS NDESCBIT)
	(ACTION STOVE-F)>

<OBJECT SOUP
	(IN KITCHEN)
	(SYNONYM SOUP POT DINNER STEW)
	(ADJECTIVE BOILING GREY)
	(DESC "pot of soup")
	(FLAGS NDESCBIT FOODBIT TRYTAKEBIT)
	(ACTION SOUP-F)>

<OBJECT KITCHEN-TABLE
	(IN KITCHEN)
	(SYNONYM TABLE PLATES PLATE BOWLS)
	(ADJECTIVE KITCHEN)
	(DESC "kitchen table")
	(FLAGS NDESCBIT)
	(ACTION KITCHEN-TABLE-F)>

<OBJECT PANTRY
	(IN KITCHEN)
	(SYNONYM PANTRY CUPBOARD)
	(ADJECTIVE PANTRY NARROW)
	(DESC "pantry")
	(FLAGS CONTBIT NDESCBIT SEARCHBIT)
	(CAPACITY 20)
	(ACTION PANTRY-F)>

<OBJECT LAMP
	(IN PANTRY)
	(SYNONYM LAMP LANTERN WICK)
	(ADJECTIVE OIL KEROSENE GLASS)
	(DESC "kerosene lamp")
	(FLAGS TAKEBIT LIGHTBIT)
	(SIZE 10)
	(ACTION LAMP-F)>

<OBJECT MATCHBOOK
	(IN PANTRY)
	(SYNONYM MATCHBOOK MATCHES MATCH)
	(ADJECTIVE PAPER)
	(DESC "book of matches")
	(FLAGS TAKEBIT READBIT)
	(SIZE 2)
	(TEXT "The cover says MORROW'S DINER, WE NEVER CLOSE. Three matches are left.")>

"---------- the living room ----------"

<OBJECT CLOCK
	(IN LIVING-ROOM)
	(SYNONYM CLOCK HANDS PENDULUM)
	(ADJECTIVE GRANDFATHER TALL)
	(DESC "grandfather clock")
	(FLAGS NDESCBIT)
	(ACTION CLOCK-F)>

<OBJECT RADIO
	(IN LIVING-ROOM)
	(SYNONYM RADIO DIAL SONG MUSIC)
	(ADJECTIVE WOODEN CABINET)
	(DESC "cabinet radio")
	(FLAGS NDESCBIT)
	(ACTION RADIO-F)>

<OBJECT PHOTO
	(IN LIVING-ROOM)
	(SYNONYM PHOTO PHOTOGRAPH FRAME MANTEL)
	(ADJECTIVE FAMILY FRAMED)
	(DESC "family photograph")
	(FLAGS NDESCBIT TRYTAKEBIT)
	(ACTION PHOTO-F)>

<OBJECT RUG
	(IN LIVING-ROOM)
	(SYNONYM RUG CARPET)
	(ADJECTIVE BRAIDED OVAL)
	(DESC "braided rug")
	(FLAGS NDESCBIT TRYTAKEBIT)
	(ACTION RUG-F)>

<OBJECT TRAP-DOOR
	(IN LIVING-ROOM)
	(SYNONYM DOOR TRAPDOOR HATCH)
	(ADJECTIVE TRAP CELLAR)
	(DESC "trap door")
	(FLAGS DOORBIT NDESCBIT INVISIBLE)
	(ACTION TRAP-DOOR-F)>

<OBJECT STAIRS
	(IN LOCAL-GLOBALS)
	(SYNONYM STAIRS STAIRCASE STAIRWAY STEPS)
	(DESC "stairs")
	(FLAGS NDESCBIT)
	(ACTION STAIRS-F)>

"---------- upstairs ----------"

<OBJECT JUNE-DOOR
	(IN UPSTAIRS-HALL)
	(SYNONYM DOOR)
	(ADJECTIVE YELLOW BEDROOM)
	(DESC "yellow door")
	(FLAGS DOORBIT NDESCBIT)
	(ACTION JUNE-DOOR-F)>

<OBJECT JUNE
	(IN JUNE-ROOM)
	(SYNONYM JUNE SISTER GIRL JUNEBUG)
	(ADJECTIVE LITTLE)
	(DESC "June")
	(FLAGS ACTORBIT NDESCBIT)
	(ACTION JUNE-F)>

<OBJECT DRAWINGS
	(IN JUNE-ROOM)
	(SYNONYM DRAWINGS DRAWING CRAYONS PICTURES)
	(ADJECTIVE CRAYON)
	(DESC "drawings")
	(FLAGS NDESCBIT READBIT)
	(ACTION DRAWINGS-F)>

<OBJECT NIGHTSTAND
	(IN PARENTS-ROOM)
	(SYNONYM NIGHTSTAND DRAWER STAND)
	(ADJECTIVE NIGHT BEDSIDE)
	(DESC "nightstand")
	(FLAGS CONTBIT NDESCBIT SEARCHBIT)
	(CAPACITY 5)>

<OBJECT DIARY
	(IN NIGHTSTAND)
	(SYNONYM DIARY JOURNAL PAGES)
	(ADJECTIVE LEATHER)
	(DESC "leather diary")
	(FLAGS READBIT TAKEBIT)
	(SIZE 3)
	(ACTION DIARY-F)>

<OBJECT MIRROR
	(IN PARENTS-ROOM)
	(SYNONYM MIRROR REFLECTION)
	(ADJECTIVE TALL VANITY)
	(DESC "mirror")
	(FLAGS NDESCBIT)
	(ACTION MIRROR-F)>

<OBJECT BED
	(IN PARENTS-ROOM)
	(SYNONYM BED SHEETS PILLOW)
	(DESC "bed")
	(FLAGS NDESCBIT)
	(ACTION BED-F)>

"---------- under the house ----------"

<OBJECT SHELVES
	(IN CELLAR)
	(SYNONYM SHELVES SHELF JARS JAR)
	(ADJECTIVE GLASS DUSTY)
	(DESC "shelves of jars")
	(FLAGS NDESCBIT)
	(ACTION SHELVES-F)>

<OBJECT DRESS
	(IN ROOT-CELLAR)
	(SYNONYM DRESS BONES BODY REMAINS)
	(ADJECTIVE GREEN FOLDED)
	(DESC "green dress")
	(FLAGS NDESCBIT TRYTAKEBIT)
	(ACTION DRESS-F)>

<OBJECT MUSIC-BOX
	(IN ROOT-CELLAR)
	(SYNONYM MUSICBOX BOX LULLABY)
	(ADJECTIVE MUSIC TIN SMALL)
	(DESC "music box")
	(FLAGS TAKEBIT)
	(SIZE 4)
	(FDESC "A small tin music box sits on the folded dress, as if someone set it there to keep.")
	(ACTION MUSIC-BOX-F)>

<OBJECT LOCKET
	(IN ROOT-CELLAR)
	(SYNONYM LOCKET NECKLACE)
	(ADJECTIVE SILVER TARNISHED)
	(DESC "silver locket")
	(FLAGS TAKEBIT)
	(SIZE 1)
	(FDESC "A silver locket is caught in the bones of one hand.")
	(ACTION LOCKET-F)>

<OBJECT ROPE
	(IN LOCAL-GLOBALS)
	(SYNONYM ROPE LINE)
	(ADJECTIVE WET FRAYED)
	(DESC "rope")
	(FLAGS NDESCBIT)
	(ACTION ROPE-F)>

"---------- rooms ----------"

<ROOM WEST-OF-HOUSE
      (IN ROOMS)
      (DESC "West of House")
      (NORTH TO NORTH-OF-HOUSE)
      (NE TO NORTH-OF-HOUSE)
      (SOUTH TO WELL-TOP)
      (SE TO WELL-TOP)
      (WEST PER FOREST-EXIT)
      (EAST "The front door is boarded from the inside. You can see the nail heads.")
      (IN "The front door is boarded from the inside. You can see the nail heads.")
      (ACTION WEST-HOUSE-F)
      (FLAGS RLANDBIT ONBIT SACREDBIT)
      (GLOBAL WHITE-HOUSE BOARDS LIT-WINDOW)>

<ROOM NORTH-OF-HOUSE
      (IN ROOMS)
      (DESC "North of House")
      (WEST TO WEST-OF-HOUSE)
      (SW TO WEST-OF-HOUSE)
      (EAST TO BEHIND-HOUSE)
      (SE TO BEHIND-HOUSE)
      (SOUTH "The windows on this side are boarded over.")
      (ACTION NORTH-HOUSE-F)
      (FLAGS RLANDBIT ONBIT SACREDBIT)
      (GLOBAL WHITE-HOUSE LIT-WINDOW)>

<ROOM BEHIND-HOUSE
      (IN ROOMS)
      (DESC "Behind House")
      (NORTH TO NORTH-OF-HOUSE)
      (NW TO NORTH-OF-HOUSE)
      (SOUTH TO WELL-TOP)
      (SW TO WELL-TOP)
      (WEST TO KITCHEN IF KITCHEN-WINDOW IS OPEN)
      (IN TO KITCHEN IF KITCHEN-WINDOW IS OPEN)
      (EAST "The field ends at a line of black trees. You don't go in there alone.")
      (ACTION BEHIND-HOUSE-F)
      (FLAGS RLANDBIT ONBIT SACREDBIT)
      (GLOBAL WHITE-HOUSE KITCHEN-WINDOW LIT-WINDOW)>

<ROOM WELL-TOP
      (IN ROOMS)
      (DESC "The Well")
      (NORTH TO BEHIND-HOUSE)
      (NE TO BEHIND-HOUSE)
      (NW TO WEST-OF-HOUSE)
      (WEST TO WEST-OF-HOUSE)
      (DOWN TO WELL-BOTTOM IF BUCKET-DOWN ELSE "The stones are slick with moss. You would need the rope down first.")
      (ACTION WELL-TOP-F)
      (FLAGS RLANDBIT ONBIT SACREDBIT)
      (GLOBAL WHITE-HOUSE GLOBAL-WATER ROPE)>

<ROOM KITCHEN
      (IN ROOMS)
      (DESC "Kitchen")
      (EAST TO BEHIND-HOUSE IF KITCHEN-WINDOW IS OPEN)
      (OUT TO BEHIND-HOUSE IF KITCHEN-WINDOW IS OPEN)
      (WEST TO LIVING-ROOM)
      (ACTION KITCHEN-F)
      (FLAGS RLANDBIT ONBIT SACREDBIT)
      (GLOBAL KITCHEN-WINDOW)>

<ROOM LIVING-ROOM
      (IN ROOMS)
      (DESC "Living Room")
      (EAST TO KITCHEN)
      (UP TO UPSTAIRS-HALL)
      (DOWN TO CELLAR IF TRAP-DOOR IS OPEN)
      (WEST "The front door is boarded from this side too. Someone used a lot of nails.")
      (ACTION LIVING-ROOM-F)
      (FLAGS RLANDBIT ONBIT SACREDBIT)
      (GLOBAL STAIRS BOARDS)>

<ROOM UPSTAIRS-HALL
      (IN ROOMS)
      (DESC "Upstairs Hall")
      (DOWN TO LIVING-ROOM)
      (NORTH TO JUNE-ROOM IF JUNE-DOOR IS OPEN)
      (IN TO JUNE-ROOM IF JUNE-DOOR IS OPEN)
      (SOUTH TO PARENTS-ROOM)
      (ACTION UPSTAIRS-HALL-F)
      (FLAGS RLANDBIT ONBIT SACREDBIT)
      (GLOBAL STAIRS)>

<ROOM JUNE-ROOM
      (IN ROOMS)
      (DESC "June's Room")
      (SOUTH TO UPSTAIRS-HALL)
      (OUT TO UPSTAIRS-HALL)
      (ACTION JUNE-ROOM-F)
      (FLAGS RLANDBIT ONBIT SACREDBIT)>

<ROOM PARENTS-ROOM
      (IN ROOMS)
      (DESC "Parents' Room")
      (NORTH TO UPSTAIRS-HALL)
      (OUT TO UPSTAIRS-HALL)
      (ACTION PARENTS-ROOM-F)
      (FLAGS RLANDBIT ONBIT SACREDBIT)>

<ROOM CELLAR
      (IN ROOMS)
      (DESC "Cellar")
      (UP TO LIVING-ROOM IF TRAP-DOOR IS OPEN)
      (EAST TO ROOT-CELLAR)
      (ACTION CELLAR-F)
      (FLAGS RLANDBIT)
      (GLOBAL STAIRS)>

<ROOM ROOT-CELLAR
      (IN ROOMS)
      (DESC "Root Cellar")
      (WEST TO CELLAR)
      (EAST TO TUNNEL)
      (ACTION ROOT-CELLAR-F)
      (FLAGS RLANDBIT)>

<ROOM TUNNEL
      (IN ROOMS)
      (DESC "Tunnel")
      (WEST TO ROOT-CELLAR)
      (EAST TO WELL-BOTTOM)
      (ACTION TUNNEL-F)
      (FLAGS RLANDBIT)>

<ROOM WELL-BOTTOM
      (IN ROOMS)
      (DESC "Bottom of the Well")
      (WEST TO TUNNEL)
      (UP TO WELL-TOP IF BUCKET-DOWN ELSE "The stones are slick with moss. Far above, the circle of sky doesn't care.")
      (ACTION WELL-BOTTOM-F)
      (FLAGS RLANDBIT ONBIT)
      (GLOBAL GLOBAL-WATER ROPE)>
